project_id = "ywirnyuvvpenzajaajkg"

[functions.generate-background]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-stranger-music]
verify_jwt = false

[functions.precache-stranger-music]
verify_jwt = false

[functions.submit-guest-book]
verify_jwt = false